// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VRP.Context;

namespace VRP.Migrations
{
    [DbContext(typeof(VrpGisDbContext))]
    partial class VrpGisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:postgis", "'postgis', '', ''")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("VRP.Model.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Point>("LatLng")
                        .HasColumnName("Location");

                    b.Property<string>("Name");

                    b.Property<int?>("WarehouseId");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("VRP.Model.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CourierId");

                    b.Property<Point>("LatLng")
                        .HasColumnName("Location");

                    b.Property<string>("Name");

                    b.Property<string>("PlaceInfo");

                    b.Property<int?>("WarehouseId");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("VRP.Model.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CapacityForCouriers");

                    b.Property<Point>("LatLng")
                        .HasColumnName("Location");

                    b.Property<string>("Name");

                    b.Property<string>("PlaceInfo");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("VRP.Model.Courier", b =>
                {
                    b.HasOne("VRP.Model.Warehouse")
                        .WithMany("Couriers")
                        .HasForeignKey("WarehouseId");
                });

            modelBuilder.Entity("VRP.Model.Package", b =>
                {
                    b.HasOne("VRP.Model.Courier")
                        .WithMany("Packages")
                        .HasForeignKey("CourierId");

                    b.HasOne("VRP.Model.Warehouse")
                        .WithMany("StoredPackages")
                        .HasForeignKey("WarehouseId");
                });
#pragma warning restore 612, 618
        }
    }
}
